export const NOTIFICATION_EVENTS = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",

  PASSWORD_RESET_OTP: "PASSWORD_RESET_OTP",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_EXPIRY_REMINDER: "PASSWORD_EXPIRY_REMINDER",

  MEAL_PLAN_GENERATED: "MEAL_PLAN_GENERATED",
  WEEKLY_SUMMARY: "WEEKLY_SUMMARY",

  FEEDBACK_RECEIVED: "FEEDBACK_RECEIVED",
  INACTIVITY_REMINDER: "INACTIVITY_REMINDER"
};
