export const NOTIFICATION_EVENTS = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",

  PASSWORD_RESET_OTP: "PASSWORD_RESET_OTP",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_EXPIRY_REMINDER: "PASSWORD_EXPIRY_REMINDER",

  MEAL_PLAN_GENERATED: "MEAL_PLAN_GENERATED",
  MEAL_CREATED: "MEAL_CREATED",
  WEEKLY_SUMMARY: "WEEKLY_SUMMARY",
  MEAL_ANALYSIS_COMPLETE: "MEAL_ANALYSIS_COMPLETE",
  HEALTH_RISK_REPORT: "HEALTH_RISK_REPORT",

  FEEDBACK_RECEIVED: "FEEDBACK_RECEIVED",
  INACTIVITY_REMINDER: "INACTIVITY_REMINDER",
  
  // New events for AI services
  AI_CHAT_RESPONSE: "AI_CHAT_RESPONSE",
  NUTRITION_RECOMMENDATION: "NUTRITION_RECOMMENDATION"
};
